


services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app

  backend:
    build:
      context: ./backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    working_dir: /app

  
