// app.js
//just test code generated by chatgpt

const express = require('express');
const { Sequelize, DataTypes } = require('sequelize');

const app = express();
const port = process.env.PORT || 3000;

// Create SQLite database instance
const sequelize = new Sequelize({
  dialect: 'sqlite',
  storage: './database.sqlite' // SQLite database file path
});

// Define Sequelize model
const User = sequelize.define('User', {
  // Define model attributes
  firstName: {
    type: DataTypes.STRING,
    allowNull: false
  },
  lastName: {
    type: DataTypes.STRING,
    allowNull: false
  },
  email: {
    type: DataTypes.STRING,
    allowNull: false,
    unique: true
  }
});

// Sync Sequelize model with database (create table if not exists)
sequelize.sync()
  .then(() => {
    console.log('Database synced');
  })
  .catch(err => {
    console.error('Database sync error:', err);
  });

// Middleware to parse JSON request body
app.use(express.json());

// Route to create a new user
app.post('/api/users', async (req, res) => {
  try {
    const { firstName, lastName, email } = req.body;
    const user = await User.create({ firstName, lastName, email });
    res.json(user);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Route to fetch all users
app.get('/api/users', async (req, res) => {
  try {
    const users = await User.findAll();
    res.json(users);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Start the server
app.listen(port, () => {
  console.log(`Server is running on port ${port}`);
});
